version: "2"

services:
  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    image: vote:oleg
    #command:  /bin/sh -c "sleep 10000"
    #volumes:
    # - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build:
      context: ./result
    command: nodemon --debug server.js
    #volumes:
    #  - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
