version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    ports:
      - "80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    command: nodemon --debug server.js
    ports:
      - "5001"
      - "5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker/Dockerfile.j
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    networks:
      - back-tier


networks:
  front-tier:
  back-tier:
